baseURL = 'https://kaepr.github.io/'
languageCode = 'en-us'
title = "Shagun Agrawal's Blog"
theme = "archie"

[params]
    mode="toggle" # color-mode → light,dark,toggle or auto
    useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
    subtitle = ""
    mathjax = true # enable MathJax support
    katex = true # enable KaTeX support

[[params.social]]
name = "GitHub"
icon = "github"
url = "https://github.com/kaepr"

[[params.social]]
name = "Twitter"
icon = "twitter"
url = "https://x.com/agrawalshagun10"

# Main menu Items

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "All posts"
url = "/posts"
weight = 2

[[menu.main]]
name = "About"
url = "/about"
weight = 3

[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
